GHC=ghc

Prisoners: Prisoners.hs
	${GHC} -O --make Prisoners.hs -fno-omit-yields -fforce-recomp -rtsopts

PrisonersRaw: PrisonersRaw.hs
	${GHC} -O --make PrisonersRaw.hs -fno-omit-yields -fforce-recomp -rtsopts
